/**
 * Auto-generated TypeScript types from backend Python models
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-types.ts
 * 
 * Source files:
 * - backend/src/models/mind_types.py
 * - backend/src/models/enums.py
 * - backend/src/models/mind.py
 * 
 * **Validates: Requirements 10.5, 10.6, 10.8, 10.9**
 */

// ============================================================================
// Enums
// ============================================================================

export type StatusEnum = 'draft' | 'frozen' | 'accepted' | 'ready' | 'active' | 'done' | 'archived' | 'obsolet' | 'deleted';

export const StatusEnum = {
  DRAFT: 'draft' as const,
  FROZEN: 'frozen' as const,
  ACCEPTED: 'accepted' as const,
  READY: 'ready' as const,
  ACTIVE: 'active' as const,
  DONE: 'done' as const,
  ARCHIVED: 'archived' as const,
  OBSOLET: 'obsolet' as const,
  DELETED: 'deleted' as const,
} as const;

export type PriorityEnum = 'low' | 'medium' | 'high' | 'critical';

export const PriorityEnum = {
  LOW: 'low' as const,
  MEDIUM: 'medium' as const,
  HIGH: 'high' as const,
  CRITICAL: 'critical' as const,
} as const;

export type SeverityEnum = 'low' | 'medium' | 'high' | 'critical';

export const SeverityEnum = {
  LOW: 'low' as const,
  MEDIUM: 'medium' as const,
  HIGH: 'high' as const,
  CRITICAL: 'critical' as const,
} as const;

export type ProbabilityEnum = 'rare' | 'unlikely' | 'possible' | 'likely' | 'certain';

export const ProbabilityEnum = {
  RARE: 'rare' as const,
  UNLIKELY: 'unlikely' as const,
  POSSIBLE: 'possible' as const,
  LIKELY: 'likely' as const,
  CERTAIN: 'certain' as const,
} as const;

export type ResourceType = 'PERSON' | 'GROUP' | 'EQUIPMENT';

export const ResourceType = {
  PERSON: 'PERSON' as const,
  GROUP: 'GROUP' as const,
  EQUIPMENT: 'EQUIPMENT' as const,
} as const;

export type AccountType = 'COST' | 'REVENUE';

export const AccountType = {
  COST: 'COST' as const,
  REVENUE: 'REVENUE' as const,
} as const;

export type TaskType = 'TASK' | 'PHASE' | 'MILESTONE' | 'WORKPACKAGE';

export const TaskType = {
  TASK: 'TASK' as const,
  PHASE: 'PHASE' as const,
  MILESTONE: 'MILESTONE' as const,
  WORKPACKAGE: 'WORKPACKAGE' as const,
} as const;

export type RequirementType = 'USER_STORY' | 'USER_NEED' | 'DESIGN_INPUT' | 'DESIGN_OUTPUT' | 'PROCESS_REQUIREMENT' | 'WORK_INSTRUCTION_REQUIREMENT';

export const RequirementType = {
  USER_STORY: 'USER_STORY' as const,
  USER_NEED: 'USER_NEED' as const,
  DESIGN_INPUT: 'DESIGN_INPUT' as const,
  DESIGN_OUTPUT: 'DESIGN_OUTPUT' as const,
  PROCESS_REQUIREMENT: 'PROCESS_REQUIREMENT' as const,
  WORK_INSTRUCTION_REQUIREMENT: 'WORK_INSTRUCTION_REQUIREMENT' as const,
} as const;

// ============================================================================
// Mind Type Interfaces
// ============================================================================

export interface Project {
  __primarylabel__: 'Project';
  uuid?: string; // Unique identifier that remains constant across all versions
  title: string; // Human-readable name for the Mind node
  version?: number; // Auto-incrementing version number
  created_at?: string;
  updated_at?: string;
  creator: string; // User identifier who created the node
  status?: StatusEnum; // Current lifecycle state
  description?: string | null; // Optional detailed description
  tags?: string[] | null; // Optional list of tags for categorization
  start_date: string; // Project start date
  end_date: string; // Project end date
  budget?: number | null; // Optional budget amount in currency units
}

export interface Task {
  __primarylabel__: 'Task';
  uuid?: string; // Unique identifier that remains constant across all versions
  title: string; // Human-readable name for the Mind node
  version?: number; // Auto-incrementing version number
  created_at?: string;
  updated_at?: string;
  creator: string; // User identifier who created the node
  status?: StatusEnum; // Current lifecycle state
  description?: string | null; // Optional detailed description
  tags?: string[] | null; // Optional list of tags for categorization
  priority: PriorityEnum; // Task priority level
  due_date?: string | null; // Optional due date for task completion
  effort?: number | null; // Work effort in hours
  duration?: number | null; // Work duration in days
  length?: number | null; // Calendar length in days
  task_type?: TaskType; // Type of task
  phase_number?: number | null;
  target_date?: string | null;
  completion_percentage?: number | null;
}

export interface Company {
  __primarylabel__: 'Company';
  uuid?: string; // Unique identifier that remains constant across all versions
  title: string; // Human-readable name for the Mind node
  version?: number; // Auto-incrementing version number
  created_at?: string;
  updated_at?: string;
  creator: string; // User identifier who created the node
  status?: StatusEnum; // Current lifecycle state
  description?: string | null; // Optional detailed description
  tags?: string[] | null; // Optional list of tags for categorization
  industry: string; // Industry sector or classification
  size?: number | null; // Optional number of employees
  founded_date?: string | null; // Optional company founding date
}

export interface Department {
  __primarylabel__: 'Department';
  uuid?: string; // Unique identifier that remains constant across all versions
  title: string; // Human-readable name for the Mind node
  version?: number; // Auto-incrementing version number
  created_at?: string;
  updated_at?: string;
  creator: string; // User identifier who created the node
  status?: StatusEnum; // Current lifecycle state
  description?: string | null; // Optional detailed description
  tags?: string[] | null; // Optional list of tags for categorization
  department_code: string; // Unique department code or identifier
  manager?: string | null; // Optional user identifier of the department manager
}

export interface Email {
  __primarylabel__: 'Email';
  uuid?: string; // Unique identifier that remains constant across all versions
  title: string; // Human-readable name for the Mind node
  version?: number; // Auto-incrementing version number
  created_at?: string;
  updated_at?: string;
  creator: string; // User identifier who created the node
  status?: StatusEnum; // Current lifecycle state
  description?: string | null; // Optional detailed description
  tags?: string[] | null; // Optional list of tags for categorization
  sender: string; // Email address of the sender
  recipients: string[]; // List of recipient email addresses
  subject: string; // Email subject line
  sent_at: string; // Timestamp when the email was sent
}

export interface Knowledge {
  __primarylabel__: 'Knowledge';
  uuid?: string; // Unique identifier that remains constant across all versions
  title: string; // Human-readable name for the Mind node
  version?: number; // Auto-incrementing version number
  created_at?: string;
  updated_at?: string;
  creator: string; // User identifier who created the node
  status?: StatusEnum; // Current lifecycle state
  description?: string | null; // Optional detailed description
  category: string; // Knowledge category or classification
  tags: string[]; // List of tags for categorization and search
  content: string; // Knowledge article content
}

export interface AcceptanceCriteria {
  __primarylabel__: 'AcceptanceCriteria';
  uuid?: string; // Unique identifier that remains constant across all versions
  title: string; // Human-readable name for the Mind node
  version?: number; // Auto-incrementing version number
  created_at?: string;
  updated_at?: string;
  creator: string; // User identifier who created the node
  status?: StatusEnum; // Current lifecycle state
  description?: string | null; // Optional detailed description
  tags?: string[] | null; // Optional list of tags for categorization
  criteria_text: string; // Detailed acceptance criteria description
  verification_method: string; // Method used to verify the criteria
  verification_status: string;
}

export interface Risk {
  __primarylabel__: 'Risk';
  uuid?: string; // Unique identifier that remains constant across all versions
  title: string; // Human-readable name for the Mind node
  version?: number; // Auto-incrementing version number
  created_at?: string;
  updated_at?: string;
  creator: string; // User identifier who created the node
  status?: StatusEnum; // Current lifecycle state
  description?: string | null; // Optional detailed description
  tags?: string[] | null; // Optional list of tags for categorization
  severity: number; // Risk severity rating 1-10
  probability: ProbabilityEnum; // Risk probability
  mitigation_plan?: string | null; // Optional risk mitigation plan
  acceptable_limit?: string | null; // Acceptable risk threshold
}

export interface Failure {
  __primarylabel__: 'Failure';
  uuid?: string; // Unique identifier that remains constant across all versions
  title: string; // Human-readable name for the Mind node
  version?: number; // Auto-incrementing version number
  created_at?: string;
  updated_at?: string;
  creator: string; // User identifier who created the node
  status?: StatusEnum; // Current lifecycle state
  description?: string | null; // Optional detailed description
  tags?: string[] | null; // Optional list of tags for categorization
  failure_mode: string; // Description of the failure mode
  effects: string; // Effects or consequences of the failure
  causes: string; // Root causes of the failure
  detection_method?: string | null; // Optional method for detecting the failure
  occurrence?: number | null; // Occurrence rating 1-10
  detectability?: number | null; // Detectability rating 1-10
}

export interface Requirement {
  __primarylabel__: 'Requirement';
  uuid?: string; // Unique identifier that remains constant across all versions
  title: string; // Human-readable name for the Mind node
  version?: number; // Auto-incrementing version number
  created_at?: string;
  updated_at?: string;
  creator: string; // User identifier who created the node
  status?: StatusEnum; // Current lifecycle state
  description?: string | null; // Optional detailed description
  tags?: string[] | null; // Optional list of tags for categorization
  requirement_type: RequirementType; // Type of requirement
  content: string; // Requirement content or text
  source?: string | null; // Source of requirement
  acceptance_criteria?: string | null; // Acceptance criteria
  compliance_standard?: string | null; // Compliance standard reference
  safety_critical?: boolean; // Safety-critical flag
}

export interface Resource {
  __primarylabel__: 'Resource';
  uuid?: string; // Unique identifier that remains constant across all versions
  title: string; // Human-readable name for the Mind node
  version?: number; // Auto-incrementing version number
  created_at?: string;
  updated_at?: string;
  creator: string; // User identifier who created the node
  status?: StatusEnum; // Current lifecycle state
  description?: string | null; // Optional detailed description
  tags?: string[] | null; // Optional list of tags for categorization
  email?: string | null; // Optional email address for the resource
  workinghours_max_per_week?: number; // Maximal working hours per week
  workinghours_per_year?: number; // Working hours per year
  efficiency?: number;
  hourly_rate?: number; // Hourly cost rate in EUR
  resource_type?: ResourceType; // Type of resource
}

export interface Journalentry {
  __primarylabel__: 'Journalentry';
  uuid?: string; // Unique identifier that remains constant across all versions
  title: string; // Human-readable name for the Mind node
  version?: number; // Auto-incrementing version number
  created_at?: string;
  updated_at?: string;
  creator: string; // User identifier who created the node
  status?: StatusEnum; // Current lifecycle state
  description?: string | null; // Optional detailed description
  tags?: string[] | null; // Optional list of tags for categorization
  severity: SeverityEnum; // Severity of the journal entry
}

export interface Booking {
  __primarylabel__: 'Booking';
  uuid?: string; // Unique identifier that remains constant across all versions
  title: string; // Human-readable name for the Mind node
  version?: number; // Auto-incrementing version number
  created_at?: string;
  updated_at?: string;
  creator: string; // User identifier who created the node
  status?: StatusEnum; // Current lifecycle state
  description?: string | null; // Optional detailed description
  tags?: string[] | null; // Optional list of tags for categorization
  hours_worked: number; // Hours worked
  booking_date?: string | null; // Date of the booking
  rate?: number | null; // Hourly rate at time of booking
  amount?: number | null;
}

export interface Sprint {
  __primarylabel__: 'Sprint';
  uuid?: string; // Unique identifier that remains constant across all versions
  title: string; // Human-readable name for the Mind node
  version?: number; // Auto-incrementing version number
  created_at?: string;
  updated_at?: string;
  creator: string; // User identifier who created the node
  status?: StatusEnum; // Current lifecycle state
  description?: string | null; // Optional detailed description
  tags?: string[] | null; // Optional list of tags for categorization
  sprint_number: number; // Sprint number
  start_date: string; // Sprint start date
  end_date: string; // Sprint end date
  goal?: string | null; // Sprint goal
  velocity?: number | null; // Sprint velocity in story points or hours
}

export interface Account {
  __primarylabel__: 'Account';
  uuid?: string; // Unique identifier that remains constant across all versions
  title: string; // Human-readable name for the Mind node
  version?: number; // Auto-incrementing version number
  created_at?: string;
  updated_at?: string;
  creator: string; // User identifier who created the node
  status?: StatusEnum; // Current lifecycle state
  description?: string | null; // Optional detailed description
  tags?: string[] | null; // Optional list of tags for categorization
  account_type?: AccountType;
}

export interface ScheduleHistory {
  __primarylabel__: 'ScheduleHistory';
  uuid?: string; // Unique identifier that remains constant across all versions
  title: string; // Human-readable name for the Mind node
  version?: number; // Auto-incrementing version number
  created_at?: string;
  updated_at?: string;
  creator: string; // User identifier who created the node
  description?: string | null; // Optional detailed description
  tags?: string[] | null; // Optional list of tags for categorization
  schedule_id: string; // Unique schedule identifier
  scheduled_at?: string;
  status?: StatusEnum; // Schedule status
  total_effort?: number | null; // Total work effort
  total_cost?: number | null; // Total project cost
  global_start?: string | null; // First task start date
  global_end?: string | null; // Last task end date
}

export interface ScheduledTask {
  __primarylabel__: 'ScheduledTask';
  uuid?: string; // Unique identifier that remains constant across all versions
  title: string; // Human-readable name for the Mind node
  version?: number; // Auto-incrementing version number
  created_at?: string;
  updated_at?: string;
  creator: string; // User identifier who created the node
  status?: StatusEnum; // Current lifecycle state
  description?: string | null; // Optional detailed description
  tags?: string[] | null; // Optional list of tags for categorization
  source_task_uuid: string; // UUID of the source INPUT Task
  scheduled_start: string; // Calculated start date
  scheduled_end: string; // Calculated end date
  scheduled_duration?: number | null; // Work duration in days
  scheduled_length?: number | null; // Calendar length in days
  is_critical?: boolean; // On critical path?
  slack_start?: number | null; // Float before start
  slack_end?: number | null; // Float before end
  base_cost?: number | null; // Base cost
  variable_cost?: number | null;
  total_cost?: number | null; // Total cost
}

// ============================================================================
// Union Types
// ============================================================================

export type Mind = Project | Task | Company | Department | Email | Knowledge | AcceptanceCriteria | Risk | Failure | Requirement | Resource | Journalentry | Booking | Sprint | Account | ScheduleHistory | ScheduledTask;

export type NodeType = 'Project' | 'Task' | 'Company' | 'Department' | 'Email' | 'Knowledge' | 'AcceptanceCriteria' | 'Risk' | 'Failure' | 'Requirement' | 'Resource' | 'Journalentry' | 'Booking' | 'Sprint' | 'Account' | 'ScheduleHistory' | 'ScheduledTask';
