"""
Auto-generated Pydantic schemas for Mind types.

This file is generated by scripts/generate_schemas.py.
DO NOT EDIT MANUALLY - changes will be overwritten.

**Validates: Requirement 1 (Schema Auto-Generation from Data Model)**
"""

from datetime import date, datetime
from uuid import UUID
from typing import Optional

from pydantic import BaseModel, EmailStr, field_serializer, field_validator

from ..models.enums import (
    StatusEnum,
    PriorityEnum,
    SeverityEnum,
    ProbabilityEnum,
    ResourceType,
    AccountType,
    TaskType,
    RequirementType,
)


class AcceptanceCriteriaCreate(BaseModel):
    """Schema for creating a AcceptanceCriteria."""

    title: str
    created_at: datetime | None = None
    creator: str
    status: StatusEnum | None = StatusEnum.DRAFT
    description: str | None = None
    tags: list[str] | None = None
    criteria_text: str
    verification_method: str
    verification_status: str

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class AcceptanceCriteriaUpdate(BaseModel):
    """Schema for updating a AcceptanceCriteria. All fields are optional."""

    title: str | None = None
    created_at: datetime | None = None
    creator: str | None = None
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    criteria_text: str | None = None
    verification_method: str | None = None
    verification_status: str | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class AcceptanceCriteriaResponse(BaseModel):
    """Schema for AcceptanceCriteria responses."""

    uuid: UUID | None = None
    title: str
    version: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    creator: str
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    criteria_text: str
    verification_method: str
    verification_status: str

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class AccountCreate(BaseModel):
    """Schema for creating a Account."""

    title: str
    created_at: datetime | None = None
    creator: str
    status: StatusEnum | None = StatusEnum.DRAFT
    description: str | None = None
    tags: list[str] | None = None
    account_type: AccountType | None = AccountType.COST

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value

    @field_serializer('account_type')
    def serialize_account_type(self, value: AccountType | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, AccountType) else value

    @field_validator('account_type', mode='before')
    @classmethod
    def validate_account_type(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return AccountType(value)
        return value



class AccountUpdate(BaseModel):
    """Schema for updating a Account. All fields are optional."""

    title: str | None = None
    created_at: datetime | None = None
    creator: str | None = None
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    account_type: AccountType | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value

    @field_serializer('account_type')
    def serialize_account_type(self, value: AccountType | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, AccountType) else value

    @field_validator('account_type', mode='before')
    @classmethod
    def validate_account_type(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return AccountType(value)
        return value



class AccountResponse(BaseModel):
    """Schema for Account responses."""

    uuid: UUID | None = None
    title: str
    version: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    creator: str
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    account_type: AccountType | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value

    @field_serializer('account_type')
    def serialize_account_type(self, value: AccountType | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, AccountType) else value

    @field_validator('account_type', mode='before')
    @classmethod
    def validate_account_type(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return AccountType(value)
        return value



class BookingCreate(BaseModel):
    """Schema for creating a Booking."""

    title: str
    created_at: datetime | None = None
    creator: str
    status: StatusEnum | None = StatusEnum.DRAFT
    description: str | None = None
    tags: list[str] | None = None
    hours_worked: float
    booking_date: date | None = None
    rate: float | None = None
    amount: float | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class BookingUpdate(BaseModel):
    """Schema for updating a Booking. All fields are optional."""

    title: str | None = None
    created_at: datetime | None = None
    creator: str | None = None
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    hours_worked: float | None = None
    booking_date: date | None = None
    rate: float | None = None
    amount: float | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class BookingResponse(BaseModel):
    """Schema for Booking responses."""

    uuid: UUID | None = None
    title: str
    version: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    creator: str
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    hours_worked: float
    booking_date: date | None = None
    rate: float | None = None
    amount: float | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class CompanyCreate(BaseModel):
    """Schema for creating a Company."""

    title: str
    created_at: datetime | None = None
    creator: str
    status: StatusEnum | None = StatusEnum.DRAFT
    description: str | None = None
    tags: list[str] | None = None
    industry: str
    size: int | None = None
    founded_date: date | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class CompanyUpdate(BaseModel):
    """Schema for updating a Company. All fields are optional."""

    title: str | None = None
    created_at: datetime | None = None
    creator: str | None = None
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    industry: str | None = None
    size: int | None = None
    founded_date: date | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class CompanyResponse(BaseModel):
    """Schema for Company responses."""

    uuid: UUID | None = None
    title: str
    version: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    creator: str
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    industry: str
    size: int | None = None
    founded_date: date | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class DepartmentCreate(BaseModel):
    """Schema for creating a Department."""

    title: str
    created_at: datetime | None = None
    creator: str
    status: StatusEnum | None = StatusEnum.DRAFT
    description: str | None = None
    tags: list[str] | None = None
    department_code: str
    manager: str | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class DepartmentUpdate(BaseModel):
    """Schema for updating a Department. All fields are optional."""

    title: str | None = None
    created_at: datetime | None = None
    creator: str | None = None
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    department_code: str | None = None
    manager: str | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class DepartmentResponse(BaseModel):
    """Schema for Department responses."""

    uuid: UUID | None = None
    title: str
    version: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    creator: str
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    department_code: str
    manager: str | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class EmailCreate(BaseModel):
    """Schema for creating a Email."""

    title: str
    created_at: datetime | None = None
    creator: str
    status: StatusEnum | None = StatusEnum.DRAFT
    description: str | None = None
    tags: list[str] | None = None
    sender: EmailStr
    recipients: list[EmailStr]
    subject: str
    sent_at: datetime

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class EmailUpdate(BaseModel):
    """Schema for updating a Email. All fields are optional."""

    title: str | None = None
    created_at: datetime | None = None
    creator: str | None = None
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    sender: EmailStr | None = None
    recipients: list[EmailStr] | None = None
    subject: str | None = None
    sent_at: datetime | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class EmailResponse(BaseModel):
    """Schema for Email responses."""

    uuid: UUID | None = None
    title: str
    version: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    creator: str
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    sender: EmailStr
    recipients: list[EmailStr]
    subject: str
    sent_at: datetime

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class FailureCreate(BaseModel):
    """Schema for creating a Failure."""

    title: str
    created_at: datetime | None = None
    creator: str
    status: StatusEnum | None = StatusEnum.DRAFT
    description: str | None = None
    tags: list[str] | None = None
    failure_mode: str
    effects: str
    causes: str
    detection_method: str | None = None
    occurrence: int | None = None
    detectability: int | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class FailureUpdate(BaseModel):
    """Schema for updating a Failure. All fields are optional."""

    title: str | None = None
    created_at: datetime | None = None
    creator: str | None = None
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    failure_mode: str | None = None
    effects: str | None = None
    causes: str | None = None
    detection_method: str | None = None
    occurrence: int | None = None
    detectability: int | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class FailureResponse(BaseModel):
    """Schema for Failure responses."""

    uuid: UUID | None = None
    title: str
    version: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    creator: str
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    failure_mode: str
    effects: str
    causes: str
    detection_method: str | None = None
    occurrence: int | None = None
    detectability: int | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class JournalentryCreate(BaseModel):
    """Schema for creating a Journalentry."""

    title: str
    created_at: datetime | None = None
    creator: str
    status: StatusEnum | None = StatusEnum.DRAFT
    description: str | None = None
    tags: list[str] | None = None
    severity: SeverityEnum

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value

    @field_serializer('severity')
    def serialize_severity(self, value: SeverityEnum) -> str:
        return value.value if isinstance(value, SeverityEnum) else value

    @field_validator('severity', mode='before')
    @classmethod
    def validate_severity(cls, value):
        if isinstance(value, str):
            return SeverityEnum(value)
        return value



class JournalentryUpdate(BaseModel):
    """Schema for updating a Journalentry. All fields are optional."""

    title: str | None = None
    created_at: datetime | None = None
    creator: str | None = None
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    severity: SeverityEnum | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value

    @field_serializer('severity')
    def serialize_severity(self, value: SeverityEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, SeverityEnum) else value

    @field_validator('severity', mode='before')
    @classmethod
    def validate_severity(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return SeverityEnum(value)
        return value



class JournalentryResponse(BaseModel):
    """Schema for Journalentry responses."""

    uuid: UUID | None = None
    title: str
    version: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    creator: str
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    severity: SeverityEnum

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value

    @field_serializer('severity')
    def serialize_severity(self, value: SeverityEnum) -> str:
        return value.value if isinstance(value, SeverityEnum) else value

    @field_validator('severity', mode='before')
    @classmethod
    def validate_severity(cls, value):
        if isinstance(value, str):
            return SeverityEnum(value)
        return value



class KnowledgeCreate(BaseModel):
    """Schema for creating a Knowledge."""

    title: str
    created_at: datetime | None = None
    creator: str
    status: StatusEnum | None = StatusEnum.DRAFT
    description: str | None = None
    tags: list[str] | None = None
    category: str
    tags: list[str]
    content: str

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class KnowledgeUpdate(BaseModel):
    """Schema for updating a Knowledge. All fields are optional."""

    title: str | None = None
    created_at: datetime | None = None
    creator: str | None = None
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    category: str | None = None
    tags: list[str] | None = None
    content: str | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class KnowledgeResponse(BaseModel):
    """Schema for Knowledge responses."""

    uuid: UUID | None = None
    title: str
    version: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    creator: str
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    category: str
    tags: list[str]
    content: str

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class ProjectCreate(BaseModel):
    """Schema for creating a Project."""

    title: str
    created_at: datetime | None = None
    creator: str
    status: StatusEnum | None = StatusEnum.DRAFT
    description: str | None = None
    tags: list[str] | None = None
    start_date: date
    end_date: date
    budget: float | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class ProjectUpdate(BaseModel):
    """Schema for updating a Project. All fields are optional."""

    title: str | None = None
    created_at: datetime | None = None
    creator: str | None = None
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    start_date: date | None = None
    end_date: date | None = None
    budget: float | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class ProjectResponse(BaseModel):
    """Schema for Project responses."""

    uuid: UUID | None = None
    title: str
    version: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    creator: str
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    start_date: date
    end_date: date
    budget: float | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class RequirementCreate(BaseModel):
    """Schema for creating a Requirement."""

    title: str
    created_at: datetime | None = None
    creator: str
    status: StatusEnum | None = StatusEnum.DRAFT
    description: str | None = None
    tags: list[str] | None = None
    requirement_type: RequirementType
    content: str
    source: str | None = None
    acceptance_criteria: str | None = None
    compliance_standard: str | None = None
    safety_critical: bool | None = False

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value

    @field_serializer('requirement_type')
    def serialize_requirement_type(self, value: RequirementType) -> str:
        return value.value if isinstance(value, RequirementType) else value

    @field_validator('requirement_type', mode='before')
    @classmethod
    def validate_requirement_type(cls, value):
        if isinstance(value, str):
            return RequirementType(value)
        return value



class RequirementUpdate(BaseModel):
    """Schema for updating a Requirement. All fields are optional."""

    title: str | None = None
    created_at: datetime | None = None
    creator: str | None = None
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    requirement_type: RequirementType | None = None
    content: str | None = None
    source: str | None = None
    acceptance_criteria: str | None = None
    compliance_standard: str | None = None
    safety_critical: bool | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value

    @field_serializer('requirement_type')
    def serialize_requirement_type(self, value: RequirementType | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, RequirementType) else value

    @field_validator('requirement_type', mode='before')
    @classmethod
    def validate_requirement_type(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return RequirementType(value)
        return value



class RequirementResponse(BaseModel):
    """Schema for Requirement responses."""

    uuid: UUID | None = None
    title: str
    version: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    creator: str
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    requirement_type: RequirementType
    content: str
    source: str | None = None
    acceptance_criteria: str | None = None
    compliance_standard: str | None = None
    safety_critical: bool | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value

    @field_serializer('requirement_type')
    def serialize_requirement_type(self, value: RequirementType) -> str:
        return value.value if isinstance(value, RequirementType) else value

    @field_validator('requirement_type', mode='before')
    @classmethod
    def validate_requirement_type(cls, value):
        if isinstance(value, str):
            return RequirementType(value)
        return value



class ResourceCreate(BaseModel):
    """Schema for creating a Resource."""

    title: str
    created_at: datetime | None = None
    creator: str
    status: StatusEnum | None = StatusEnum.DRAFT
    description: str | None = None
    tags: list[str] | None = None
    email: str | None = None
    workinghours_max_per_week: float | None = 40.0
    workinghours_per_year: float | None = 1700.0
    efficiency: float | None = 1.0
    hourly_rate: float | None = 100.0
    resource_type: ResourceType | None = ResourceType.PERSON

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value

    @field_serializer('resource_type')
    def serialize_resource_type(self, value: ResourceType | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, ResourceType) else value

    @field_validator('resource_type', mode='before')
    @classmethod
    def validate_resource_type(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return ResourceType(value)
        return value



class ResourceUpdate(BaseModel):
    """Schema for updating a Resource. All fields are optional."""

    title: str | None = None
    created_at: datetime | None = None
    creator: str | None = None
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    email: str | None = None
    workinghours_max_per_week: float | None = None
    workinghours_per_year: float | None = None
    efficiency: float | None = None
    hourly_rate: float | None = None
    resource_type: ResourceType | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value

    @field_serializer('resource_type')
    def serialize_resource_type(self, value: ResourceType | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, ResourceType) else value

    @field_validator('resource_type', mode='before')
    @classmethod
    def validate_resource_type(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return ResourceType(value)
        return value



class ResourceResponse(BaseModel):
    """Schema for Resource responses."""

    uuid: UUID | None = None
    title: str
    version: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    creator: str
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    email: str | None = None
    workinghours_max_per_week: float | None = None
    workinghours_per_year: float | None = None
    efficiency: float | None = None
    hourly_rate: float | None = None
    resource_type: ResourceType | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value

    @field_serializer('resource_type')
    def serialize_resource_type(self, value: ResourceType | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, ResourceType) else value

    @field_validator('resource_type', mode='before')
    @classmethod
    def validate_resource_type(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return ResourceType(value)
        return value



class RiskCreate(BaseModel):
    """Schema for creating a Risk."""

    title: str
    created_at: datetime | None = None
    creator: str
    status: StatusEnum | None = StatusEnum.DRAFT
    description: str | None = None
    tags: list[str] | None = None
    severity: int
    probability: ProbabilityEnum
    mitigation_plan: str | None = None
    acceptable_limit: str | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value

    @field_serializer('probability')
    def serialize_probability(self, value: ProbabilityEnum) -> str:
        return value.value if isinstance(value, ProbabilityEnum) else value

    @field_validator('probability', mode='before')
    @classmethod
    def validate_probability(cls, value):
        if isinstance(value, str):
            return ProbabilityEnum(value)
        return value



class RiskUpdate(BaseModel):
    """Schema for updating a Risk. All fields are optional."""

    title: str | None = None
    created_at: datetime | None = None
    creator: str | None = None
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    severity: int | None = None
    probability: ProbabilityEnum | None = None
    mitigation_plan: str | None = None
    acceptable_limit: str | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value

    @field_serializer('probability')
    def serialize_probability(self, value: ProbabilityEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, ProbabilityEnum) else value

    @field_validator('probability', mode='before')
    @classmethod
    def validate_probability(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return ProbabilityEnum(value)
        return value



class RiskResponse(BaseModel):
    """Schema for Risk responses."""

    uuid: UUID | None = None
    title: str
    version: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    creator: str
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    severity: int
    probability: ProbabilityEnum
    mitigation_plan: str | None = None
    acceptable_limit: str | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value

    @field_serializer('probability')
    def serialize_probability(self, value: ProbabilityEnum) -> str:
        return value.value if isinstance(value, ProbabilityEnum) else value

    @field_validator('probability', mode='before')
    @classmethod
    def validate_probability(cls, value):
        if isinstance(value, str):
            return ProbabilityEnum(value)
        return value



class ScheduleHistoryCreate(BaseModel):
    """Schema for creating a ScheduleHistory."""

    title: str
    created_at: datetime | None = None
    creator: str
    status: StatusEnum | None = StatusEnum.DRAFT
    description: str | None = None
    tags: list[str] | None = None
    schedule_id: str
    scheduled_at: datetime | None = None
    status: StatusEnum | None = StatusEnum.DONE
    total_effort: float | None = None
    total_cost: float | None = None
    global_start: datetime | None = None
    global_end: datetime | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class ScheduleHistoryUpdate(BaseModel):
    """Schema for updating a ScheduleHistory. All fields are optional."""

    title: str | None = None
    created_at: datetime | None = None
    creator: str | None = None
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    schedule_id: str | None = None
    scheduled_at: datetime | None = None
    status: StatusEnum | None = None
    total_effort: float | None = None
    total_cost: float | None = None
    global_start: datetime | None = None
    global_end: datetime | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class ScheduleHistoryResponse(BaseModel):
    """Schema for ScheduleHistory responses."""

    uuid: UUID | None = None
    title: str
    version: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    creator: str
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    schedule_id: str
    scheduled_at: datetime | None = None
    status: StatusEnum | None = None
    total_effort: float | None = None
    total_cost: float | None = None
    global_start: datetime | None = None
    global_end: datetime | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class ScheduledTaskCreate(BaseModel):
    """Schema for creating a ScheduledTask."""

    title: str
    created_at: datetime | None = None
    creator: str
    status: StatusEnum | None = StatusEnum.DRAFT
    description: str | None = None
    tags: list[str] | None = None
    source_task_uuid: UUID
    scheduled_start: datetime
    scheduled_end: datetime
    scheduled_duration: float | None = None
    scheduled_length: float | None = None
    is_critical: bool | None = False
    slack_start: float | None = None
    slack_end: float | None = None
    base_cost: float | None = None
    variable_cost: float | None = None
    total_cost: float | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class ScheduledTaskUpdate(BaseModel):
    """Schema for updating a ScheduledTask. All fields are optional."""

    title: str | None = None
    created_at: datetime | None = None
    creator: str | None = None
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    source_task_uuid: UUID | None = None
    scheduled_start: datetime | None = None
    scheduled_end: datetime | None = None
    scheduled_duration: float | None = None
    scheduled_length: float | None = None
    is_critical: bool | None = None
    slack_start: float | None = None
    slack_end: float | None = None
    base_cost: float | None = None
    variable_cost: float | None = None
    total_cost: float | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class ScheduledTaskResponse(BaseModel):
    """Schema for ScheduledTask responses."""

    uuid: UUID | None = None
    title: str
    version: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    creator: str
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    source_task_uuid: UUID
    scheduled_start: datetime
    scheduled_end: datetime
    scheduled_duration: float | None = None
    scheduled_length: float | None = None
    is_critical: bool | None = None
    slack_start: float | None = None
    slack_end: float | None = None
    base_cost: float | None = None
    variable_cost: float | None = None
    total_cost: float | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class SprintCreate(BaseModel):
    """Schema for creating a Sprint."""

    title: str
    created_at: datetime | None = None
    creator: str
    status: StatusEnum | None = StatusEnum.DRAFT
    description: str | None = None
    tags: list[str] | None = None
    sprint_number: int
    start_date: date
    end_date: date
    goal: str | None = None
    velocity: float | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class SprintUpdate(BaseModel):
    """Schema for updating a Sprint. All fields are optional."""

    title: str | None = None
    created_at: datetime | None = None
    creator: str | None = None
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    sprint_number: int | None = None
    start_date: date | None = None
    end_date: date | None = None
    goal: str | None = None
    velocity: float | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class SprintResponse(BaseModel):
    """Schema for Sprint responses."""

    uuid: UUID | None = None
    title: str
    version: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    creator: str
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    sprint_number: int
    start_date: date
    end_date: date
    goal: str | None = None
    velocity: float | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value



class TaskCreate(BaseModel):
    """Schema for creating a Task."""

    title: str
    created_at: datetime | None = None
    creator: str
    status: StatusEnum | None = StatusEnum.DRAFT
    description: str | None = None
    tags: list[str] | None = None
    priority: PriorityEnum
    due_date: date | None = None
    effort: float | None = None
    duration: float | None = None
    length: float | None = None
    task_type: TaskType | None = 'TASK'
    phase_number: int | None = None
    target_date: date | None = None
    completion_percentage: float | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value

    @field_serializer('priority')
    def serialize_priority(self, value: PriorityEnum) -> str:
        return value.value if isinstance(value, PriorityEnum) else value

    @field_validator('priority', mode='before')
    @classmethod
    def validate_priority(cls, value):
        if isinstance(value, str):
            return PriorityEnum(value)
        return value

    @field_serializer('task_type')
    def serialize_task_type(self, value: TaskType | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, TaskType) else value

    @field_validator('task_type', mode='before')
    @classmethod
    def validate_task_type(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return TaskType(value)
        return value



class TaskUpdate(BaseModel):
    """Schema for updating a Task. All fields are optional."""

    title: str | None = None
    created_at: datetime | None = None
    creator: str | None = None
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    priority: PriorityEnum | None = None
    due_date: date | None = None
    effort: float | None = None
    duration: float | None = None
    length: float | None = None
    task_type: TaskType | None = None
    phase_number: int | None = None
    target_date: date | None = None
    completion_percentage: float | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value

    @field_serializer('priority')
    def serialize_priority(self, value: PriorityEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, PriorityEnum) else value

    @field_validator('priority', mode='before')
    @classmethod
    def validate_priority(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return PriorityEnum(value)
        return value

    @field_serializer('task_type')
    def serialize_task_type(self, value: TaskType | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, TaskType) else value

    @field_validator('task_type', mode='before')
    @classmethod
    def validate_task_type(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return TaskType(value)
        return value



class TaskResponse(BaseModel):
    """Schema for Task responses."""

    uuid: UUID | None = None
    title: str
    version: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    creator: str
    status: StatusEnum | None = None
    description: str | None = None
    tags: list[str] | None = None
    priority: PriorityEnum
    due_date: date | None = None
    effort: float | None = None
    duration: float | None = None
    length: float | None = None
    task_type: TaskType | None = None
    phase_number: int | None = None
    target_date: date | None = None
    completion_percentage: float | None = None

    @field_serializer('status')
    def serialize_status(self, value: StatusEnum | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, StatusEnum) else value

    @field_validator('status', mode='before')
    @classmethod
    def validate_status(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return StatusEnum(value)
        return value

    @field_serializer('priority')
    def serialize_priority(self, value: PriorityEnum) -> str:
        return value.value if isinstance(value, PriorityEnum) else value

    @field_validator('priority', mode='before')
    @classmethod
    def validate_priority(cls, value):
        if isinstance(value, str):
            return PriorityEnum(value)
        return value

    @field_serializer('task_type')
    def serialize_task_type(self, value: TaskType | None) -> str | None:
        if value is None:
            return None
        return value.value if isinstance(value, TaskType) else value

    @field_validator('task_type', mode='before')
    @classmethod
    def validate_task_type(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            return TaskType(value)
        return value


